### ISSUE TITLE
No matching distribution found for blockcanvas>=4.0.3.dev (from ets)

### ISSUE THREAD

**Issue by gauravgary** [enthought/blockcanvas#11]
C:\Users\username>pip install ets
Collecting ets
  Using cached ets-4.4.4.tar.gz
Collecting apptools>=4.2.1.dev (from ets)
  Using cached apptools-4.4.0.zip
Collecting blockcanvas>=4.0.3.dev (from ets)
  Could not find a version that satisfies the requirement blockcanvas>
 (from ets) (from versions: )
No matching distribution found for blockcanvas>=4.0.3.dev (from ets)

**Comment by mdickinson** [comment]
Closing here; blockcanvas has long been inactive. I'll open an issue on the `ets` tracker.
