### ISSUE TITLE
testsuite state in current 4.0.3

### ISSUE THREAD

**Issue by idella** [enthought/blockcanvas#8]
These ets packages are quite a maize in dir structure.  The following are what I can't yet figure out and get into any sane state.

 ets3to4 .
        nosetests -I test_generator\* \
                -I test_generatorr_nested\* \
                -I test_remote\* 

.S.........FSF................................F...F.................................................E..............................................................F...............ES....EEE......SSS........S........................................

1) ERROR: test_for_single_celem_enum_iterable (blockcanvas.function_tools.tests.test_function_call_group.FunctionCallGroupTestCase)

thru to

  File "/var/tmp/portage/dev-python/blockcanvas-4.0.3-r1/work/blockcanvas-4.0.3-python2_7/lib/blockcanvas/function_tools/group_spec.py", line 288, in _get_call_signature
    celem_call_signature = self.curr_elemts[0].call_signature
IndexError: list index out of range

5) ERROR: Failure: ImportError (No module named distribution.distribution)

thru to

  File "/var/tmp/portage/dev-python/blockcanvas-4.0.3-r1/work/blockcanvas-4.0.3-python2_7/lib/blockcanvas/interactor/stochastic_interactor.py", line 11, in <module>
    from traits.util.distribution.distribution import \
ImportError: No module named distribution.distribution

6) ERROR: Failure: ImportError (No module named distribution.distribution)

thru to

  File "/var/tmp/portage/dev-python/blockcanvas-4.0.3-r1/work/blockcanvas-4.0.3-python2_7/lib/blockcanvas/interactor/stochastic_interactor.py", line 11, in <module>
    from traits.util.distribution.distribution import \
ImportError: No module named distribution.distribution

7) ERROR: Failure: ImportError (No module named distribution.distribution)

thru to

  File "/var/tmp/portage/dev-python/blockcanvas-4.0.3-r1/work/blockcanvas-4.0.3-python2_7/lib/blockcanvas/interactor/stochastic_item.py", line 11, in <module>
    from traits.util.distribution.distribution import \
ImportError: No module named distribution.distribution

8) ERROR: Failure: ImportError (No module named api)

  File "/var/tmp/portage/dev-python/blockcanvas-4.0.3-r1/work/blockcanvas-4.0.3-python2_7/lib/blockcanvas/model/numeric_model.py", line 17, in <module>
    from traits.api \
ImportError: No module named api

9) FAIL: test_unbound_inputs (blockcanvas.block_display.tests.block_restrict_test_case.BlockRestrictestCase)

```
self.assertEqual(sub_block.outputs, set(['c', 'd', 'add', 'mul']))
```

AssertionError: Items in the second set but not the first:
'mul'
'add'

10) FAIL: test_add_function (blockcanvas.block_display.tests.test_execution_model.ExecutionModelTestCase)

AssertionError: '\ndef foo(a, b): \n    x, y = (a, b)\n    return x, y\n\nx_, y_ = foo(1, 2)' != '\ndef foo(a, b): \n    x, y = (a, b)\n    return x, y\n\nx, y = foo(1, 2)'

11) FAIL: Doctest: blockcanvas.canvas.simple_math.distance_to_line

File "/var/tmp/portage/dev-python/blockcanvas-4.0.3-r1/work/blockcanvas-4.0.3-python2_7/lib/blockcanvas/canvas/simple_math.py", line 95, in blockcanvas.canvas.simple_math.distance_to_line
Failed example:
    distance_to_line([0,0],[1,1],[0,1])
Expected:
    0.70710678118654757
Got:
    0.7071067811865476

12) FAIL: Doctest: blockcanvas.canvas.simple_math.subtract

File "/var/tmp/portage/dev-python/blockcanvas-4.0.3-r1/work/blockcanvas-4.0.3-python2_7/lib/blockcanvas/canvas/simple_math.py", line 58, in blockcanvas.canvas.simple_math.subtract
Failed example:
    subtract([2,1],[.5,.1])
Expected:
    [1.5, 0.90000000000000002]
Got:
    [1.5, 0.9]

13 )FAIL: test_convert_function_proper_docstring (blockcanvas.function_tools.tests.test_rest_html.RestHTMLTestCase)

```
self.assertNotEqual(html1.find('[km/s]'), -1)
```

AssertionError: -1 == -1

Ran 250 tests in 5.166s
FAILED (SKIP=8, errors=5, failures=5)

Nice & clear??  Well the alternate is to offer to upload a build log.

1) test_for_single_celem_enum_iterable just looks like it plain gets the wrong answer or outcome.

2-4) With the -I (ignored) test files listed after call to nosetests add another 3.
These 3 have in common
    from py.magic import greenlet
ImportError: No module named magic

Where do you get these import modules from?  package py has no such module called magic between current 1,4,9 - 1,4,12 correct me if I'm wrong.  Is the test so old it predates any modern version of py?
I have a package
/usr/include/python2.7/greenlet
anything related to that perhaps.  I don't know.  Tried it and it doesn't seem to fit.

Currently I have almost digested the diffs between the 3.s and the watershed 4.0s.
Enter etsproxy.
Most all of the deps I have listed for blockcanvas are version 4.0 or greater.
Still there are a couple of files in the package that get updated with the ets3to4 utility. Note I ran it before the call to nosetests. Now which and where are the right dir paths?????

5) from traits.util.distribution.distribution import
ok;  This has undergone the ets3to4 and I am supposedly looking at a version 4 path of a module ......distribution.distribution.py
I have
~/cvsPortage/gentoo-x86/dev-python/blockcanvas $ qfile distribution
dev-python/etsproxy (/usr/lib64/python2.7/site-packages/enthought/util/distribution)

similarly 

~/cvsPortage/gentoo-x86/dev-python/blockcanvas $ qfile distribution.py
dev-python/etsproxy (/usr/lib64/python2.7/site-packages/enthought/util/distribution/distribution.py)

Now this is where you REALLY lose me.  What is being imported is ...distribution.distribution, not plain distribution, so the only option is the 
etsproxy (/usr/lib64/python2.7/site-packages/enthought/util/distribution/distribution.py)

which is the backport of the version 3 paths!!!!!!!!!  I (en)thought the idea here was to make version4 paths by use of the ets3to4, not the other way around, Either way, BOTH "from traits.util.distribution.distribution" && "from enthought.util.distribution.distribution" are wrong.

WILL THE REAL PATHWAY  please step forward.

6) && 7) ditto

8) from traits.api;   Just to make it more interesting, a right path is declared a wrong path!!!!!! 

[D] dev-python/traits
Installed versions:  4.3.0-r1(14:09:15 11/04/13)

$ qlist dev-python/traits | grep api                                    yields 
/usr/lib64/python2.7/site-packages/traits/api.py

AND

~/cvsPortage/gentoo-x86/dev-python/blockcanvas $ python2.7 -c "from traits import api"
yields an effective import by py2.7 on the CL!!.  The path appears VALID and it failed anyway

Tilt!!

9) & 10) just fail it seems with the wrong outcome.
11) is a doctest.

This is the version limited to use of the version >= 4. pathways.
I've spared you the versions limited to the passee 3.0 versions
12) ditto  9) & 10)
13) ditto 11)

**Comment by mdickinson** [comment]
blockcanvas is unmaintained; closing this issue
